version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "3268:4000"
    environment:
      DB_HOST: bd
      DB_PORT: 1000
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - app-network
    depends_on:
      - bd

  dashboard:
    build: ./dashboard
    ports:
      - "4139:80"
    networks:
      - app-network
    depends_on:
      - api

  bd:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "1000:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: {}